var lang_strings = {
	'Rename': 'Renommer',
	'Delete': 'Supprimer',
	'Edit': 'Éditer',
	'Directory name': 'Nom du répertoire',
	'File name': 'Nom du fichier',
	'New file name': 'Nom du nouveau fichier',
	'Upload this file?': 'Envoyer ce fichier ?',
	'Confirm delete?': 'Confirmer la suppression ?',
	'Close': 'Fermer',
	'Files': 'Fichiers',
	'New directory': 'Nouveau répertoire',
	'New text file': 'Nouveau fichier texte',
	'Upload file': 'Envoyer un fichier',
	'Download': 'Télécharger',
	'B': 'o', // Bytes unit
	'%d minutes ago': 'il y a %d minutes',
	'%d hours ago': 'il y a %d heures',
	'Yesterday, %s': 'Hier à %s',
	'OK': 'OK',
	'Back': 'Retour',
	'Sort by name': 'Trier par nom',
	'Sort by date': 'Trier par date',
	'Sort by size': 'Trier par taille',
	'Download all files': 'Tout télécharger'
};
