var lang_strings = {
	'Rename': 'Renommer',
	'Delete': 'Supprimer',
	'Edit': 'Éditer',
	'Directory name': 'Nom du répertoire',
	'File name': 'Nom du fichier',
	'New file name': 'Nom du nouveau fichier',
	'Upload this file?': 'Envoyer ce fichier ?',
	'Confirm delete?': 'Confirmer la suppression ?',
	'No file is selected': 'Aucun fichier sélectionné',
	'Close': 'Fermer',
	'Cancel': 'Annuler',
	'Autosave': 'Enregistrement automatique',
	'Save and close': 'Enregistrer et fermer',
	'Your changes have not been saved. Do you want to cancel WITHOUT saving?': 'Vos modifications n\'ont pas été enregistrées. Est-ce que vous souhaitez annuler SANS ENREGISTRER ?',
	'Modified': 'Modifié',
	'Saved': 'Enregistré',
	'Files': 'Fichiers',
	'Upload files': 'Envoyer des fichiers',
	'New': 'Nouveau',
	'Directory': 'Répertoire',
	'Text file': 'Fichier texte',
	'Office document': 'Bureautique',
	'Text': 'Document',
	'Spreadsheet': 'Tableur',
	'Presentation': 'Présentation',
	'Drawing': 'Dessin',
	'Download': 'Télécharger',
	'Download as ZIP': 'Télécharger en ZIP',
	'B': 'o', // Bytes unit
	'%d minutes ago': 'il y a %d minutes',
	'%d hours ago': 'il y a %d heures',
	'Yesterday, %s': 'Hier à %s',
	'OK': 'OK',
	'Back': 'Retour',
	'My files': 'Mes fichiers',
	'Name': 'Nom',
	'Date': 'Date',
	'Size': 'Taille',
	'Selected:': 'Sélectionné :',
	'%d files': '%d fichiers',
	'%d directories': '%d répertoires',
};
