browser.lang_strings.fr = {
	'Rename': 'Renommer',
	'Delete': 'Supprimer',
	'Edit': 'Éditer',
	'Folder name': 'Nom du répertoire',
	'Create this folder': 'Créer ce répertoire',
	'Create this file': 'Créer ce fichier',
	'File name': 'Nom du fichier',
	'New file name': 'Nom du nouveau fichier',
	'Upload this file?': 'Envoyer ce fichier ?',
	'Confirm delete?': 'Confirmer la suppression ?',
	'Move to trash?': 'Déplacer vers la corbeille ?',
	'Move to trash': 'Déplacer à la corbeille',
	'No file is selected': 'Aucun fichier sélectionné',
	'Close': 'Fermer',
	'Cancel': 'Annuler',
	'Autosave': 'Enregistrement automatique',
	'Save and close': 'Enregistrer et fermer',
	'Your changes have not been saved. Do you want to cancel WITHOUT saving?': 'Vos modifications n\'ont pas été enregistrées. Est-ce que vous souhaitez annuler SANS ENREGISTRER ?',
	'Modified': 'Modifié',
	'Saved': 'Enregistré',
	'Files': 'Fichiers',
	'Upload files': 'Envoyer des fichiers',
	'New': 'Nouveau',
	'Folder': 'Répertoire',
	'Text file': 'Fichier texte',
	'Office document': 'Bureautique',
	'Text': 'Document',
	'Spreadsheet': 'Tableur',
	'Presentation': 'Présentation',
	'Drawing': 'Dessin',
	'Download': 'Télécharger',
	'Download as ZIP': 'Télécharger en ZIP',
	'B': 'o', // Bytes unit
	'%d minutes ago': 'il y a %d minutes',
	'%d hours ago': 'il y a %d heures',
	'Yesterday, %s': 'Hier à %s',
	'OK': 'OK',
	'Back': 'Retour',
	'My files': 'Mes fichiers',
	'Name': 'Nom',
	'Date': 'Date',
	'Size': 'Taille',
	'Selected:': 'Sélectionné :',
	'%d files': '%d fichiers',
	'%d directories': '%d répertoires',
	'Move': 'Déplacer',
	'Copy': 'Copier',
	'Move here': 'Déplacer ici',
	'Copy here': 'Copier ici',
	'Cannot move to the same folder': 'Impossible de déplacer vers le même répertoire',
	'View as list': 'Voir en liste',
	'View as gallery': 'Voir en galerie',
	'%s free': '%s libres',
	'%s used (%s of %s)': '%s utilisé (%s sur %s)',
	'Share': 'Partager',
	'Shared': 'Partagé',
	'Open share options': 'Ouvrir les options de partage',
	'Copied!': 'Copié !',
	'Send this link to your contacts:': 'Transmettez ce lien à vos contacts :',
	'Share options': 'Options de partage',
	'A public share link will be created, allowing access to these files without a login.': 'Un lien de partage public sera créé, permettant d\'accéder à ces fichiers sans avoir à se connecter.',
	'What can people do with this link?': 'Que pourront faire les personnes qui auront ce lien de partage ?',
	'Only view and download': 'Seulement voir et télécharger',
	'Edit, view and download': 'Modifier, voir et télécharger',
	'When will this link expire?': 'Combien de temps ce lien doit rester valide ?',
	'One hour': 'Une heure',
	'One day': 'Un jour',
	'One week': 'Une semaine',
	'One month': 'Un mois',
	'3 months': '3 mois',
	'6 months': '6 mois',
	'One year': 'Un an',
	'Never': 'Jamais',
	'Ask for a password?': 'Demander un mot de passe ?',
	'If supplied, people will need to enter this password to access the shared files.': 'Si renseigné, les personnes devront entrer ce mot de passe pour accéder au partage.',
	'Create share link': 'Créer le partage'
};
